# name: workflow
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main 

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       # Setup the environment
#       - uses: actions/checkout@v2
#       - uses: actions/setup-go@v2
#         with:
#           stable: 'false'
#           go-version: '1.21.7'
#       # Start linting
#       - name: linter
#         run: |
#           curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
#           golangci-lint run
name: workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Setup the environment
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.21.7'
      - name: Verify Go Installation
        run: go version
      - name: Verify Go Installation Files
        run: |
          echo "Searching for ';' in log.go"
          grep -n ';' $(go env GOROOT)/src/log/log.go

          echo "Searching for '[' in log.go"
          grep -n '\[' $(go env GOROOT)/src/log/log.go
      # Start linting
      - name: linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
          golangci-lint run
