name: linter workflow
on:
  push:
    - main
    - master
  pull_request:
    - main 
    - master
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # setup the environment 
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.21.7'
      # start linting
      - name: linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0

          golangci-lint run          